# Generated by Django 5.1.7 on 2025-03-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='sys_menus',
        ),
        migrations.AlterModelTable(
            name='role',
            table='sys_roles',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='sys_userinfo',
        ),
    ]
